[package]
name = "ibig"
version = "0.2.0"
authors = ["Tomek Czajka <tczajka@gmail.com>"]
edition = "2018"
description = "A big integer library with good performance"
keywords = ["bigint", "bignum", "mathematics"]
categories = ["mathematics", "no-std"]
license = "MIT"
repository = "https://github.com/tczajka/ibig-rs"
homepage = "https://github.com/tczajka/ibig-rs"
readme = "README.md"

[dependencies]
static_assertions = "1.1"
rand = { version = "0.8.3", default-features = false, optional = true }
num-traits = { version = "0.2.14", default-features = false, optional = true }

[dev-dependencies]
rand = "0.8.3"

[features]
default = ["std", "rand", "num-traits"]

# Interface with the std library.
std = []

# Deprecated. They don't do anything. Use --cfg force_bits=... instead.
force-16-bit = []
force-32-bit = []
force-64-bit = []

[[test]]
name = "random"
required-features = ["rand"]

[[bench]]
name = "benchmarks"
required-features = ["rand"]
