[package]
name = "ibig"
version = "0.1.0"
authors = ["Tomek Czajka <tczajka@gmail.com>"]
edition = "2018"
description = "Big integer library"
keywords = ["bigint", "bignum", "mathematics"]
categories = ["mathematics", "no-std"]
license = "MIT"
repository = "https://github.com/tczajka/ibig-rs"
homepage = "https://github.com/tczajka/ibig-rs"
readme = "README.md"

[dependencies.ascii]
version = "1.0"
default-features = false

[dependencies.rand]
version = "0.8"
default-features = false
optional = true

[dev-dependencies]
rand = "0.8"

[features]
default = ["std", "rand"]

# Interface with the std library.
std = []

[[test]]
name = "random"
required-features = ["rand"]

[[bench]]
name = "benchmarks"
required-features = ["rand"]
