[package]
name = "ibig"
version = "0.0.1"
authors = ["Tomek Czajka <tczajka@gmail.com>"]
edition = "2018"
description = "Big integer library"
keywords = ["bigint", "bignum", "mathematics"]
categories = ["mathematics", "no-std"]
license = "MIT"
repository = "https://github.com/tczajka/ibig-rs"
homepage = "https://github.com/tczajka/ibig-rs"
readme = "README.md"

[dependencies]
ascii = "1.0.0"

[features]
default = ["std"]

# Interface with the std library.
std = []
