[package]
name = "ibig"
version = "0.0.0"
authors = ["Tomek Czajka <tczajka@gmail.com>"]
edition = "2018"
description = "Big integer library"
keywords = ["bigint", "bignum", "mathematics"]
categories = ["mathematics", "no-std"]
license = "MIT"
repository = "https://github.com/tczajka/ibig-rs"
homepage = "https://github.com/tczajka/ibig-rs"

[dependencies]
